{{- if .Values.batch.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "batch.fullname" . }}
  labels:
    {{- include "batch.labels" . | nindent 4 }}
spec:
  strategy:
    type: {{ .Values.batch.deploymentStrategy }}
  {{- if not .Values.batch.autoscaling.enabled }}
  replicas: {{ .Values.batch.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "batch.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
        prometheus.io/path: '/vdyp-batch/actuator/prometheus'
      labels:
        {{- include "batch.labels" . | nindent 8 }}
    spec:
      {{- if .Values.batch.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.batch.podSecurityContext | nindent 12 }}
      {{- end }}
      terminationGracePeriodSeconds: 300  # 5min
      containers:
        - name: {{ include "batch.fullname" . }}
          {{- if .Values.batch.securityContext }}
          securityContext:
            {{- toYaml .Values.batch.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.global.registry }}/{{ .Values.global.repository }}/batch:{{ .Values.global.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ default "Always" .Values.batch.imagePullPolicy }}
          envFrom:
            - secretRef:
                name: {{.Release.Name}}
          env:
            - name: LOG_LEVEL
              value: info
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.batch.env.SPRING_PROFILES_ACTIVE | quote }}
            - name: SERVER_PORT
              value: "8081"
            - name: COMS_BASE_URL
              value: {{ .Values.backend.env.COMS_BASE_URL | quote }}
            - name: COMS_S3_ACCESSKEYID
              value: {{ .Values.coms.env.OBJECTSTORAGE_ACCESSKEYID | quote }}
            - name: COMS_S3_SECRETACCESSKEY
              value: {{ .Values.coms.env.OBJECTSTORAGE_SECRETACCESSKEY | quote }}
            - name: COMS_S3ACCESS_BUCKET
              value: {{ .Values.coms.env.OBJECTSTORAGE_BUCKET | quote }}
            - name: COMS_S3ACCESS_ENDPOINT
              value: {{ .Values.coms.env.OBJECTSTORAGE_ENDPOINT | quote }}
            - name: COMS_BASICAUTH_USERNAME
              value: {{ .Values.coms.env.BASICAUTH_USERNAME | quote }}
            - name: COMS_BASICAUTH_PASSWORD
              value: {{ .Values.coms.env.BASICAUTH_PASSWORD | quote }}
            - name: VDYP_BASE_URL
              value: {{ .Values.frontend.env.BACKEND_URL | quote }}
            - name: KEYCLOAK_CLIENT_ID
              value: {{ .Values.frontend.env.VITE_SSO_CLIENT_ID | quote }}
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backend.env.OIDC_CLIENT_SECRET_SECRET_NAME }}
                  key: {{ .Values.backend.env.OIDC_CLIENT_SECRET_SECRET_KEY }}
            - name: KEYCLOAK_TOKEN_URI
              value: "{{ .Values.backend.env.QUARKUS_OIDC_AUTH_SERVER_URL}}/protocol/openid-connect/token"

          ports:
            - name: http
              containerPort: {{ .Values.batch.service.targetPort }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /vdyp-batch/actuator/health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 10
          livenessProbe:
            successThreshold: 1
            failureThreshold: 5
            httpGet:
              path: /vdyp-batch/actuator/health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 1250m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 256Mi
      {{- with .Values.batch.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.batch.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
