name: Openshift Batch deploy/update
run-name: Deploy Batch module to ${{ inputs.ENVIRONMENT_NAME}}

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT_NAME:
        required: true
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  build-batch-image:
    name: Build Batch Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      tag: ${{ steps.build.outputs.tag }}
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push batch image
        id: build
        uses: bcgov-nr/action-builder-ghcr@v2.2.0
        with:
          package: batch
          tag: ${{ inputs.ENVIRONMENT_NAME }}-${{ github.run_number }}
          tag_fallback: ${{ inputs.ENVIRONMENT_NAME }}-latest
          token: ${{ secrets.GITHUB_TOKEN }}
          build_context: .
          build_file: ./batch/Dockerfile

  deploy-batch:
    name: Deploy Batch to OpenShift
    needs: build-batch-image
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.ENVIRONMENT_NAME }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: copy batch chart files
        run: mkdir staging && cp -r charts/app staging/app

      #Explicit install of oc cli tool
      - name: Install oc
        uses: redhat-actions/oc-installer@v1

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: https://api.silver.devops.gov.bc.ca:6443
          openshift_token: ${{secrets.oc_token}}
          namespace: ${{ secrets.oc_namespace }}

      - name: zip and install helm chart
        run: |
          cd staging && tar -czvf app.tar.gz app
          helm upgrade -i vdyp-${{inputs.ENVIRONMENT_NAME}} ./app.tar.gz \
            --values ./app/values-${{inputs.ENVIRONMENT_NAME}}.yaml \
            --set global.repository=${{ github.repository }} \
            --set global.tag=${{ needs.build-batch-image.outputs.tag }} \
            --set batch.enabled=true
